### ISSUE TITLE
Why static functions in Geolocation?

### ISSUE THREAD

**Issue by stephanvierkant** [jeroendesloovere/geolocation-php-api#5]
You're using static functions in Geolocation.php, but I can't see why. Why not use $this->doCall() ?

I think it should be easier to set some defaults (i.e. the API key) and reuse those values in multiple requests.

Something like this (when using your Bundle):
```
$geolocation = $this->get('jeroendesloovere.geolocation);
$geolocation->set('ApiKey', 'oij2ri230r8934uvtr9n349tr8984fn');

$address = $geolocation->getAddress(51.0363935, 3.7121008);
$geo = $geolocation->getCoordinates('Koningin Maria Hendrikaplein', '1', 'Gent', '9000', 'belgië');
```

**Comment by jeroendesloovere** [comment]
This is something from in the old days.
I've changed this in the [latest release](https://github.com/jeroendesloovere/geolocation-php-api/releases/tag/1.3.1).
