### ISSUE TITLE
SSL certificate problem:

### ISSUE THREAD

**Issue by eldelassombras** [jeroendesloovere/geolocation-php-api#8]
Please help me solve this problem:

<h4>An uncaught Exception was encountered</h4>

<p>Type: JeroenDesloovere\Geolocation\GeolocationException</p>
<p>Message: SSL certificate problem: unable to get local issuer certificate</p>
<p>Filename: C:\wamp\www\geocoding\vendor\jeroendesloovere\geolocation-php-api\src\Geolocation.php</p>
<p>Line Number: 77</p>

gracias.

**EDIT:** 
add the following curl options in the doCall function and solve the problem, 
```
curl_setopt($curl, CURLOPT_SSL_VERIFYHOST, 0);
curl_setopt($curl, CURLOPT_SSL_VERIFYPEER, 0);
```
but I am not sure if it is suitable for the server. Please consider a more elegant and safe solution.

saludos.

**Comment by jeroendesloovere** [comment]
Hi there, thanks for your issue.
Since the last release https is activated by @apalethorpe.

It would be nice if you could create a PR-fix for your issue.
